services:
  # 1. Spring Boot API
  api:
    build: .
    container_name: fontogether_api
    ports:
      - "444:444"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - font-net

  # 2. PostgreSQL 데이터베이스
  postgres:
    image: postgres:16-alpine # 가볍고 안정적인 Alpine 리눅스 기반 이미지
    container_name: fontogether_db_container
    ports:          # 포트 매핑 설정                      배포 시에 무조건 지워야 함!!!!!!!
      - "5432:5432" # 로컬 포트 : 컨테이너 포트 연결,       배포 시에 무조건 지워야 함!!!!!!!
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # application.yml 설정과 맞춰주세요
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db_data:/var/lib/postgresql/data # DB 데이터를 로컬 폴더에 영구 저장 (컨테이너 꺼도 데이터 유지)
    networks:
      - font-net

  # 3. pgAdmin (웹에서 DB를 관리하는 툴 - 선택 사항)
  pgadmin:
    image: dpage/pgadmin4
    container_name: fontogether_admin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - font-net

networks:
  font-net:
    driver: bridge